name: LayoutEnhancer
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - matplotlib>=3.2.2
  - numpy>=1.21.5
  - python>=3.7.11
  - pytorch>=1.10.2+cu111
  - torchvision>=0.11.3+cu111
  - transformers>=4.11.3