general:
    max_furniture: 20
    res: 256
    set_name: "3dfront_bedrooms"
    suffix_name: ""
    order_switch: 1
paths:
    path_input_data: "./data/input"
    path_output_data: "./data/output"
    path_3dfront_data: "./data/3dfront"
    path_trained_models: "./models"
network:
    model_name: "3dfront_bed_V2_overlap"
    use_ergo: True
    use_weight: False
    do_validate: True
    eval_ergo_loss: True
    use_alt_loss: True
    epochs: 10
    lr: 0.0001
    batch_size: 32
    n_layer: 12
    n_head: 8
    n_embd: 256
    continue_train: False
    continue_epoch: -1
    init_model: null
    init_model_epoch: "best"
    device: "cuda"
synthesis:
    n_scenes: 10
    top_p: 0.9
    top_k: 0
    max_noncat: True
    max_windoor: False
    collision_check: False
    recon_epoch: "best"
    house_name: "Bed_V2O_Room"